using System.Text;

namespace Novolis.Avalonia.Packaging.Inno;

/// <summary>Builds an Inno Setup script from publish output metadata.</summary>
public sealed class InnoScriptGenerator
{
    /// <summary>Installer product name shown to users.</summary>
    public required string AppName { get; init; }

    /// <summary>Version written into the installer metadata.</summary>
    public required string AppVersion { get; init; }

    /// <summary>Folder containing the published app payload.</summary>
    public required string PublishDir { get; init; }

    /// <summary>Executable name launched by the installer shortcuts.</summary>
    public required string AppExeName { get; init; }

    /// <summary>Directory where Inno writes the compiled installer.</summary>
    public required string OutputDir { get; init; }

    /// <summary>Installer application identifier used for upgrades.</summary>
    public string AppId { get; init; } = "Novolis.Audio.Live.Studio";

    /// <summary>Windows Start Menu group name.</summary>
    public string DefaultGroupName { get; init; } = "Novolis Audio Live";

    /// <summary>Installer output filename without extension.</summary>
    public string OutputBaseFilename { get; init; } = "NovolisAudioLiveSetup";

    /// <summary>Per-user installation directory suffix under LocalAppData\Programs.</summary>
    public string InstallDirName { get; init; } = @"Novolis\Novolis Audio Live";

    /// <summary>Emits the Inno Setup script as text.</summary>
    public string Generate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(AppName);
        ArgumentException.ThrowIfNullOrWhiteSpace(AppVersion);
        ArgumentException.ThrowIfNullOrWhiteSpace(PublishDir);
        ArgumentException.ThrowIfNullOrWhiteSpace(AppExeName);
        ArgumentException.ThrowIfNullOrWhiteSpace(OutputDir);
        ArgumentException.ThrowIfNullOrWhiteSpace(AppId);
        ArgumentException.ThrowIfNullOrWhiteSpace(DefaultGroupName);
        ArgumentException.ThrowIfNullOrWhiteSpace(OutputBaseFilename);
        ArgumentException.ThrowIfNullOrWhiteSpace(InstallDirName);

        var publish = PublishDir.TrimEnd('\\', '/');
        var sb = new StringBuilder();
        sb.AppendLine("; Generated by Novolis.Avalonia.Packaging.Inno");
        sb.AppendLine("[Setup]");
        sb.AppendLine($"AppId={AppId}");
        sb.AppendLine($"AppName={AppName}");
        sb.AppendLine($"AppVersion={AppVersion}");
        sb.AppendLine($"DefaultDirName={{localappdata}}\\Programs\\{InstallDirName}");
        sb.AppendLine($"DefaultGroupName={DefaultGroupName}");
        sb.AppendLine($"OutputBaseFilename={OutputBaseFilename}");
        sb.AppendLine($"OutputDir={OutputDir}");
        sb.AppendLine("PrivilegesRequired=lowest");
        sb.AppendLine("DisableProgramGroupPage=yes");
        sb.AppendLine("WizardStyle=modern");
        sb.AppendLine("ArchitecturesAllowed=x64compatible");
        sb.AppendLine("ArchitecturesInstallIn64BitMode=x64");
        sb.AppendLine("Compression=lzma2");
        sb.AppendLine("SolidCompression=yes");
        sb.AppendLine($"UninstallDisplayIcon={{app}}\\{AppExeName}");
        sb.AppendLine();
        sb.AppendLine("[Tasks]");
        sb.AppendLine("Name: \"desktopicon\"; Description: \"Create a &desktop icon\"; GroupDescription: \"Additional icons:\"; Flags: unchecked");
        sb.AppendLine();
        sb.AppendLine("[Files]");
        sb.AppendLine($"Source: \"{publish}\\*\"; DestDir: \"{{app}}\"; Flags: ignoreversion recursesubdirs createallsubdirs");
        sb.AppendLine();
        sb.AppendLine("[Icons]");
        sb.AppendLine($"Name: \"{{autoprograms}}\\{DefaultGroupName}\"; Filename: \"{{app}}\\{AppExeName}\"");
        sb.AppendLine($"Name: \"{{autodesktop}}\\{DefaultGroupName}\"; Filename: \"{{app}}\\{AppExeName}\"; Tasks: desktopicon");
        sb.AppendLine();
        sb.AppendLine("[Run]");
        sb.AppendLine($"Filename: \"{{app}}\\{AppExeName}\"; Description: \"Launch {AppName}\"; Flags: nowait postinstall skipifsilent");
        return sb.ToString();
    }
}
