Generated by Novolis.Avalonia.Packaging.Inno
[Setup]
AppId=Novolis.Audio.Live.Studio
AppName=Novolis Audio Live
AppVersion=2026.1.6.1234
DefaultDirName={localappdata}\Programs\Novolis\Novolis Audio Live
DefaultGroupName=Novolis Audio Live
OutputBaseFilename=NovolisAudioLiveSetup-2026.1.6.1234-win-x64
OutputDir=C:\Users\frank\AppData\Local\Temp\novolis-live-installer-smoke\installer
PrivilegesRequired=lowest
DisableProgramGroupPage=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64
Compression=lzma2
SolidCompression=yes
UninstallDisplayIcon={app}\Novolis.Audio.Live.Studio.exe
[Tasks]
Name: "desktopicon"
Description: "Create a &desktop icon"
GroupDescription: "Additional icons:"
Flags: unchecked
[Files]
Source: "C:\Users\frank\AppData\Local\Temp\novolis-live-installer-smoke\app\*"
DestDir: "{app}"
Flags: ignoreversion recursesubdirs createallsubdirs
[Icons]
Name: "{autoprograms}\Novolis Audio Live"
Filename: "{app}\Novolis.Audio.Live.Studio.exe"
Name: "{autodesktop}\Novolis Audio Live"
Filename: "{app}\Novolis.Audio.Live.Studio.exe"
Tasks: desktopicon
[Run]
Filename: "{app}\Novolis.Audio.Live.Studio.exe"
Description: "Launch Novolis Audio Live"
Flags: nowait postinstall skipifsilent
