<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Controls\Novolis.Avalonia.Controls.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Studio\Novolis.Avalonia.Studio.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Rendering\Novolis.Avalonia.Rendering.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Raylib\Novolis.Avalonia.Raylib.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Packaging.Inno\Novolis.Avalonia.Packaging.Inno.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Markdown\Novolis.Avalonia.Markdown.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.StarMap\Novolis.Avalonia.StarMap.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Briefing\Novolis.Avalonia.Briefing.csproj" />
  </ItemGroup>
</Project>
