<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>LiveAvalonia</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="..\..\..\novolis-audio\src\Novolis.Audio.Live\Novolis.Audio.Live.csproj" />
    <ProjectReference Include="..\..\..\novolis-audio\src\Novolis.Audio.Live.Protocol\Novolis.Audio.Live.Protocol.csproj" />
    <ProjectReference Include="..\..\..\novolis-audio\src\Novolis.Audio.Live.Repl\Novolis.Audio.Live.Repl.csproj" />
    <ProjectReference Include="..\..\..\novolis-audio\src\Novolis.Audio.Live.Visuals\Novolis.Audio.Live.Visuals.csproj" />
    <ProjectReference Include="..\..\..\novolis-audio\src\Novolis.Audio.MusicTheory\Novolis.Audio.MusicTheory.csproj" />
    <ProjectReference Include="..\..\..\novolis-audio\src\Novolis.Audio.Patterns\Novolis.Audio.Patterns.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Live\Novolis.Avalonia.Live.csproj" />
  </ItemGroup>
</Project>
