<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Novolis.Audio.Live.Studio</AssemblyName>
    <RootNamespace>LiveAvalonia</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Novolis.Audio.Live" />
    <PackageReference Include="Novolis.Audio.Live.Dsl" />
    <PackageReference Include="Novolis.Audio.Live.Protocol" />
    <PackageReference Include="Novolis.Audio.Live.Visuals" />
    <PackageReference Include="Novolis.Audio.MusicTheory" />
    <PackageReference Include="Novolis.Audio.Patterns" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Live\Novolis.Avalonia.Live.csproj" />
  </ItemGroup>
</Project>
