<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Novolis.Avalonia.Unit.Live</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Novolis.Audio.Live" />
    <ProjectReference Include="..\..\src\Novolis.Avalonia.Live\Novolis.Avalonia.Live.csproj" />
  </ItemGroup>
</Project>
